services:
  postgres:
    image: postgres:16
    container_name: innoviahub-postgres

    environment:
      POSTGRES_DB: innoviahub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d innoviahub"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./backend/api
      dockerfile: Dockerfile

    container_name: innoviahub-api

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080

      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=innoviahub;Username=postgres;Password=postgres

      Jwt__Key: ${JWT_KEY}

    ports:
      - "5197:8080"

    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: innoviahub-frontend

    ports:
      - "3000:80"

    depends_on:
      - api

volumes:
  postgres_data:
